### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#1]
Если я пр. понял то по ум-ю плагин не работает
И только если я что то в menu file поправлю- работает 
лучше дать команду- а- активировать меню плага. б- убрать. в- открыть menu file

**Comment by kvichans** [comment]
Не правильно
Он не работает пока в settings не появится либо menu.json, либо файл на который указывает опц "config_menus_from"
Доделаю, чтобы menu.json переносился при **первом** запуске из папки плагина в settings.

**Comment by kvichans** [comment]
> лучше дать команды

Да, хорошее дело
