### ISSUE TITLE
Issue which gives AV in Cuda

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#13]
http://forum.wincmd.ru/viewtopic.php?p=114850#114850
Stanislav сообщает issue- оно крешит программу при зажатии ctrl+tab, неприятно

что править и кому?

**Comment by Alexey-T** [comment]
фикс- Одна строка вместо всего в init.py

```
from .cd_config_menu import Command
```

**Comment by Alexey-T** [comment]
фикс еще надо- не читать файл в on_focus, это дает AV (из-за медленности?)- один раз читать опцию в `def __init__`.

**Comment by kvichans** [comment]
Похоже, что причина не плагине, а глубоко в Куд. Ситуация сильно напоминает проблемы с on_key, содержащем print-ы.
Да, можно в этом месте убрать из on_focus обращение к файлу. Но это же не решение, это заплатка.

**Comment by kvichans** [comment]
Вся технология перехвата событий под ударом - не понятно как ей пользоваться, что можно и что нельзя делать в `on_...` методах

**Comment by Alexey-T** [comment]
Вы правы-я если увижу баг,я посм в дебагере, пока не могу

**Comment by kvichans** [comment]
fix
