### ISSUE TITLE
Update for Cuda

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#15]
Cuda has 2 items: a)renamed "groups- 1+2 horz", b)new "groups- 1+2 vert"

**Comment by Alexey-T** [comment]
Хочется правки всех issue,билд могу сделать я

**Comment by kvichans** [comment]
Сделал все и собрал релиз

**Comment by Alexey-T** [comment]
Ок, спсб

**Comment by kvichans** [comment]
Только есть проблема: плагин не может навязать пользователю новый набор из menu.json. Команда "groups- 1+2 horz" в новом наборе есть, но если у пользователя уже работал плагин, эта команда у него не появится

**Comment by Alexey-T** [comment]
Можно думать как версию в файл писать,как в Тулах..

**Comment by kvichans** [comment]
не понял - чем это поможет?

**Comment by Alexey-T** [comment]
в общем терпимо.

**Comment by kvichans** [comment]
Главное: пользователь **руками** может править свой `menu.json`
Из-за этого плагин не в состоянии туда что-то добавлять/удалять.

**Comment by kvichans** [comment]
ок
