### ISSUE TITLE
Новые пункты

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#16]
новые подменю-пункты "Языки","темы"
- надо бы добавить в default menu
- учтите
  
  "recents" - recent-files submenu
  "themes" - color-themes submenu
  "langs" - translations submenu

**Comment by kvichans** [comment]
todo

**Comment by kvichans** [comment]
Большая переделка.
1. Появилась команда для сохранения текущих меню в JSON. Новый формат!
2. Старые настройки будут работать, но они не будут развиваться.

Файл menu.json больше не нужен - его аналог можно создать в любой момент на месте.

**Comment by Alexey-T** [comment]
в зипе файл menu.json нужен?

**Comment by kvichans** [comment]
нет, это рудимент
оставил его, так как старый формат еще работает, но не развивается
