### ISSUE TITLE
Send menu to toolbar

### ISSUE THREAD

**Issue by c-sanchez** [kvichans/cuda_config_menu#19]
Why not (if possible) send the menu bar to a menu button? like on moderm web browsers, maybe a button on toolbar or along with tab bar (like list tabs button).
So you can obtain something of extra space :)

**Comment by kvichans** [comment]
Yes. It is my dream too. I think menu "hamburger" can be placed not only in toolbar (my toolbar hidden): app title or statusbar are also good.

But the plugin cannot do that.

**Comment by Alexey-T** [comment]
no. Cud can do it. Find place of "toolmenu:" in API 2 times.

**Comment by Alexey-T** [comment]
pls close? button Hamburger is already in Cuda.

**Comment by kvichans** [comment]
OK
But "my dream" is continueing only a dream - Hamburger blocks my Cuda
