### ISSUE TITLE
Problem with upgrade

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_config_menu#2]
В конфигураторе `menu.json` используются имена из `cudatext_cmd.py`. Если эти имена меняются, то возникает проблема, как это донести до пользователей.
Например, сегодня имена 
`cmd_Encoding_utf8_Reload`
`cmd_Encoding_utf8_NoReload`
поменялись на 
`cmd_Encoding_utf8bom_Reload`
`cmd_Encoding_utf8bom_NoReload`
Предлагаю ввести запрет на переименования

**Comment by Alexey-T** [comment]
хмм. лучше смотрите плс, на изм-я файла- https://github.com/Alexey-T/CudaText/commits/master/app/py/cudatext_cmd.py

**Comment by kvichans** [comment]
Вы не поняли
Я-то смогу в _своем_ menu.json поправить, когда вылезет ошибка "нет такой команды".
А что будет делать пользователь?

**Comment by Alexey-T** [comment]
Он увидит "баг в плагине", сори
