### ISSUE TITLE
Test with Cud1.4.5

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#20]
changed Themes sub; now it has 2 subs
new ids for it
- 'themes-ui';
- 'themes-syntax';

chd also dialog for themes. now 2 cmds to call 2 dialogs.

**Comment by Alexey-T** [comment]
cmd_DialogColors       = 2532 #deprecated
new used:
cmd_DialogThemeUi       = 2552
cmd_DialogThemeSyntax   = 2553

**Comment by kvichans** [comment]
Проход по новому умолчательному меню дает
  `,{"cap":"&Color themes", "hint":"_themes"}`
Но этот ключ `_themes` не восстанавливает два подменю внутри `Color themes`.

Похоже поддержка `_themes` разрушена.

**Comment by Alexey-T** [comment]
added fix, to GH.
added hints _themes-ui, _themes-syntax
