### ISSUE TITLE
Dialog too narrow

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#22]
Оч.тесный диалог- имя файла не умещается

![menu-smal](https://cloud.githubusercontent.com/assets/4154978/23943348/978248be-0988-11e7-8113-bf3e763b983c.png)

**Comment by kvichans** [comment]
Не может быть ширины достаточной, чтобы полный путь всегда умещался.
Уже нормально - все надписи читаются без проблем

**Comment by Alexey-T** [comment]
Ok
