### ISSUE TITLE
"add" to menu

### ISSUE THREAD

**Issue by TomBraider42** [kvichans/cuda_config_menu#23]
cd_config_menu.py line 151:
i added an "if line" to not clear the menu if "how" set to "add"
```
if mnu_dict.get('how', 'add') == 'clear':
    app.app_proc(app.PROC_MENU_CLEAR, top_id)
```

**Comment by Alexey-T** [comment]
if "how" set to "add", then get() gets "add" and next code still works ok. (No need to fix)

**Comment by TomBraider42** [comment]
right, but there was no line, i added it:
`if mnu_dict.get('how', 'add') == 'clear':`

**Comment by Alexey-T** [comment]
It is solved?

**Comment by TomBraider42** [comment]
I don't know, don't use the plugin anymore.

**Comment by Alexey-T** [comment]
@kvichans Pls close?

**Comment by kvichans** [comment]
не понял что просят
мб Том не знает, что все пп меню заполняются заново - clear не нужен

**Comment by Alexey-T** [comment]
Тогда закроем
