### ISSUE TITLE
Use new api, dont use deprecated

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#24]
У себя правил-
заменял             
`app.app_proc(           app.PROC_MENU_ADD, f('{};{};{}', prnt_id, hnt, cap))`
на 
`app.menu_proc(id_action=app.MENU_ADD, id_menu=prnt_id, command=hnt, caption=cap)`

**Comment by kvichans** [comment]
С какой версии АПИ это началось?
Если еще пользуются более старым Куд, то получается мне нужно держать обе ветки кода?

**Comment by Alexey-T** [comment]
С версии 1.0.172, появилось menu-proc

**Comment by Alexey-T** [comment]
Нужно просить новую версию апи в плаге.

**Comment by kvichans** [comment]
Большая переделка. ToDo
