### ISSUE TITLE
Dont work on Cud 1.10

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#26]
Чистая установка
заходим в длг плагина.

- кнопка Create запрещена.
- нажал Help- странное сообщ. Need existed file. "existing" надо. *Какой файл*
- кнопка Open дает ошибку

```
Python 3.5.2
OK config menus from "/home/user/Downloads/cud_old/settings/menu.json"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/Downloads/cud_old/py/cuda_config_menu/cd_config_menu.py", line 438, in dlg_config
    btn, vals, chds = dlg_wrapper(_('Config menu'), 5+350+5, 5+190+5, cnts, vals, focus_cid='file')
  File "/home/user/Downloads/cud_old/py/cuda_config_menu/cd_plug_lib.py", line 497, in dlg_wrapper
    aid     = cnts[btn_i]['cid']
KeyError: 'cid'
```

**Comment by kvichans** [comment]
Какая версия АПИ в этом "чистом Куд 1.10"?

**Comment by Alexey-T** [comment]
184.

**Comment by kvichans** [comment]
Плаг работает только с 185

1. Теперь вижу, что забыл добавить проверку на min АПИ. Добавил.
2. Проблему на чистом Куд повторил. Разбираюсь

**Comment by kvichans** [comment]
fixed - бета в ГХ
Протестируйте

**Comment by kvichans** [comment]
Проблемы
>- нажал Help- странное сообщ. Need existed file. "existing" надо. Какой файл
>- кнопка Open дает ошибку

Не повторил. Они остались?

**Comment by Alexey-T** [comment]
Cud 1.10 уже не запускает плаг.

**Comment by Alexey-T** [comment]
Cud 1.11 работает ОК
