### ISSUE TITLE
Bug report on forum

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#27]
http://synwrite.sourceforge.net/forums/viewtopic.php?p=10782#p10782
Перевести длинно, не переведу

**Comment by Alexey-T** [comment]
решено?

**Comment by kvichans** [comment]
это вопрос не ко мне - только Alex842 может прояснить

**Comment by Alexey-T** [comment]
можно закрыть- Alex842 напишет на форум если что. я там спрошу.
