### ISSUE TITLE
don't put full filename to SaveAs dialog

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#29]
"Create config" button- wish-- put only short name "menu.json" with initial dir.
now i see this - full name -
![all-name](https://user-images.githubusercontent.com/4154978/35980703-6bcc3f4a-0cfc-11e8-8cd1-235558f27637.png)

**Comment by kvichans** [comment]
подумаю

**Comment by Alexey-T** [comment]
вроде решено?

**Comment by kvichans** [comment]
нет
сейчас поправлю
