### ISSUE TITLE
dont do this API check

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#30]
if app.app_api_version()<MIN_API_VER: return app.msg_status(_('Need update CudaText'))
это config_menu()
Т.е. это равно проверке api= в install.inf

**Comment by kvichans** [comment]
Да, здесь это уместно.
Перенесу

**Comment by Alexey-T** [comment]
это решено?

**Comment by Alexey-T** [comment]
вроде решено?

**Comment by kvichans** [comment]
да, теперь проверка в inf
