### ISSUE TITLE
Need check for filename or lexername

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#31]
config_menus() -не нашел прорвеку `ed.get_filename()!=''`
или `ed.get_prop(PROP_LEXER_FILE)!=''`.
Это бы ускорило плаг, может? из-за лишних on_focus.

**Comment by kvichans** [comment]
Какое влияние у свойства 
ed.get_filename()!=''
на работу этого плагина?

**Comment by Alexey-T** [comment]
Куд делает пустой таб и делает on_focus- тут имя пустое... потом грузит файл

**Comment by kvichans** [comment]
А как мне отличить on_focus на этом состоянии (перед открытием) от on_focus на уже существующий таб, не связанный с файлом?

**Comment by Alexey-T** [comment]
Проверил и сори , не вижу лишних дёрганий onfocus с пустым табом

**Comment by Alexey-T** [comment]
Может ещё дать проверку prop-lexer-file?

**Comment by kvichans** [comment]
Поясните цель проверки

**Comment by Alexey-T** [comment]
Не читать конфиг и файл меню если лескера нет

**Comment by kvichans** [comment]
Это будет ошибкой! 
Например, у меня самого обычно открыт файл (большой *.log), для которого lexer = None

**Comment by Alexey-T** [comment]
для этого файла у вас есть конфиг меню?

**Comment by kvichans** [comment]
Как это вообще возможно? 
Ответ: нет, я ожидаю, что при работе с содержимым этого файла будет основное меню. То есть если я перехожу в него из файла со спец.меню, то нужно вернуть основное

**Comment by Alexey-T** [comment]
OK, согласен
