### ISSUE TITLE
Weird code

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#32]
помоему, так не пишут.
```
+    mn_cfg_json = mn_cfg_json \
+                    if mn_cfg_json else \
+                  apx.get_opt('config_menus_from', DEF_MENU_CFG_FILE, apx.CONFIG_LEV_USER) \
```

**Comment by kvichans** [comment]
"На вкус и цвет все фломастеры разные"
Давайте обсуждать конкретнее.

**Comment by Alexey-T** [comment]
обычно пишут
if not f: f = smth;

**Comment by kvichans** [comment]
В таком же стиле написаны еще десятки мест в моих плагах.

PS Это тема для разговора между кодерами в курилке - чтобы время бежало незаметнее. Здесь нет проблемы

**Comment by kvichans** [comment]
Сообразил, как перевести разговор в русло "обмен опытом"
Предложите not weird замену для такой конструкции
```python
x = x \
      if x else \
    a1 \
      if condition1 else \
    a2 \
      if condition2 else \
    y 
```

**Comment by Alexey-T** [comment]
```
if not x:
  x = a1 if c1 else a2 if c2 else y
```

**Comment by kvichans** [comment]
1. А теперь представте, что каждое из выражений `a`, `c1`, `a1`, `c2`, `y` это длинный фрагмент. Вы продолжите считать, что запись в одну строку удобна?
2. В вашем варианте использована конструкция `if cond: state`, а в моем только оператор `val if val else val` в правой части присваивания. Мой вариант позволяет перенести все вместе в любое место где требуется значение. Ваш - нет
3. Количество проверок у обоих вариантов совпадает, а оптимизацию "исключить присваивание себе" можно поручить среде выполнения

**Comment by Alexey-T** [comment]
OK
