### ISSUE TITLE
fix language

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#34]
"Select" button -> "Browse"
"Open" btn -> "Edit"

tooltips for checkboxes- 
"Apply menu once on CudaText start"
"Apply menu (common or lexer specific) when file tab gets focus"

**Comment by Alexey-T** [comment]
"Apply now" button tooltip -- 
"Apply menu file now.
Shift+click - perform syntax checking of JSON file."

**Comment by kvichans** [comment]
fixed
