### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by actforjason** [kvichans/cuda_config_menu#38]
> [
  {"cap":"", "hint":"top", "sub": [
      {"cap":"文件 ", "hint":"top-file", "sub": [
          {"cap":"新建文件", "cmd":"cmd_FileNew"}
         ,{"cap":"从模板新建文件...", "cmd":"cmd_FileNewMenu"}

![image](https://user-images.githubusercontent.com/57058325/195983720-3e8daf99-86b3-4576-9130-fd4a14177bbc.png)

**Comment by Alexey-T** [comment]
@kvichans

**Comment by Alexey-T** [comment]
Open plugin's all .py files.

find places of `open` (whole word!)
and add 'encoding' param there in all open() calls:
`open(filename, encoding='UTF-8')` .
Helps?

**Comment by Alexey-T** [comment]
I found 3 places in 2 py files!

**Comment by actforjason** [comment]
Yes, it works.
