### ISSUE TITLE
menu ui

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#4]
Пока неудобно-если поставил плаг он просто поменял меню..
в Куд добавилось в меню. а тут не видно. из-за плага. Нужно сделать комм 1- которая запретит исп-ть конфиг menu.json, комм 2- которая включит menu.json

```
Menu config>
    Don't use menu config
    Use menu config
    Edit menu config
```

тогда не надо опций?

**Comment by kvichans** [comment]
Подумаю.
