### ISSUE TITLE
incorr command code

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#6]
{"cap":"Copy current line"      ,"cmd":"cCommand_ClipboardCopy"}
Не тот код команды (это просто Копир. -надо копир. строку)

**Comment by kvichans** [comment]
Мне не угадать какая команда лежит за командой меню.
Может просто укажете нужное имя?

**Comment by Alexey-T** [comment]
cmd_CopyLine

**Comment by kvichans** [comment]
ок, заменю
