### ISSUE TITLE
incorr command, Delete

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#9]
вместо команды **KeyDelete
надо исп-ть cCommand_TextDeleteSelection (в menu.json)-оно не делетит если нет выдел-я

**Comment by kvichans** [comment]
Заменил

**Comment by Alexey-T** [comment]
Edit/Delete--то же

**Comment by kvichans** [comment]
Что? Дайте точное имя

**Comment by Alexey-T** [comment]
,"top-edit":
 {"cap":"Delete"                     ,"cmd":"cCommand_KeyDelete"}
поменяйте плиз. Так же

**Comment by Alexey-T** [comment]
не решено!

```
,"top-edit":
    ,   {"cap":"Delete"                     ,"cmd":"cCommand_KeyDelete"}
```
